import type { Project, Testimonial, Skill, Service } from '@/types'

// Replace youtubeId values with your actual YouTube video IDs
// Replace imageSrc values with your actual thumbnail/graphic design image paths
export const PROJECTS: Project[] = [
  // ─── Podcast ───
  {
    id: 'p1',
    title: 'The Mindset Show',
    category: 'Podcast',
    year: '2024',
    thumbnail: '/images/projects/podcast-1.jpg',
    description: 'Full podcast episode edit with dynamic cuts, captions, and b-roll integration.',
    tags: ['Premiere Pro', 'Captions', 'B-Roll'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'p2',
    title: 'Creator Talks Ep.12',
    category: 'Podcast',
    year: '2024',
    thumbnail: '/images/projects/podcast-2.jpg',
    description: 'Multi-cam podcast edit with animated lower-thirds and smooth transitions.',
    tags: ['Multi-cam', 'After Effects', 'Audio Mix'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'p3',
    title: 'Finance Friday Podcast',
    category: 'Podcast',
    year: '2024',
    thumbnail: '/images/projects/podcast-3.jpg',
    description: 'Clean corporate podcast style with motion graphics and data overlays.',
    tags: ['Motion Graphics', 'Premiere Pro'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'p4',
    title: 'Health & Hustle Pod',
    category: 'Podcast',
    year: '2023',
    thumbnail: '/images/projects/podcast-4.jpg',
    description: 'Energetic podcast edit with viral clip highlights and social cuts.',
    tags: ['Premiere Pro', 'Social Clips'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'p5',
    title: 'Tech Deep Dive',
    category: 'Podcast',
    year: '2023',
    thumbnail: '/images/projects/podcast-5.jpg',
    description: 'Long-form tech podcast with screen recordings, transitions, and chapter markers.',
    tags: ['Screen Record', 'Chapters', 'Premiere Pro'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'p6',
    title: 'Startup Stories Ep.8',
    category: 'Podcast',
    year: '2023',
    thumbnail: '/images/projects/podcast-6.jpg',
    description: 'Interview-style edit with cinematic color grade and dynamic zoom cuts.',
    tags: ['Color Grade', 'Zoom Cuts'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'p7',
    title: 'Daily Grind Podcast',
    category: 'Podcast',
    year: '2023',
    thumbnail: '/images/projects/podcast-7.jpg',
    description: 'Fast-paced podcast highlights reel optimized for social media sharing.',
    tags: ['Highlights', 'Social Media'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'p8',
    title: 'Real Estate Rundown',
    category: 'Podcast',
    year: '2024',
    thumbnail: '/images/projects/podcast-8.jpg',
    description: 'Professional real estate podcast with property footage integration.',
    tags: ['B-Roll', 'Premiere Pro', 'LUT'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'p9',
    title: 'Gaming Legends Pod',
    category: 'Podcast',
    year: '2024',
    thumbnail: '/images/projects/podcast-9.jpg',
    description: 'Gaming podcast with gameplay overlays, memes, and animated reactions.',
    tags: ['After Effects', 'Gameplay', 'Memes'],
    youtubeId: 'dQw4w9WgXcQ',
  },

  // ─── Educational ───
  {
    id: 'e1',
    title: 'Editing Masterclass',
    category: 'Educational',
    year: '2024',
    thumbnail: '/images/projects/edu-1.jpg',
    description: 'Complete editing tutorial with screen recordings, annotations, and step-by-step walkthroughs.',
    featured: true,
    tags: ['Screen Record', 'After Effects', 'Tutorial'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'e2',
    title: 'Color Grading 101',
    category: 'Educational',
    year: '2024',
    thumbnail: '/images/projects/edu-2.jpg',
    description: 'Before-after color grading tutorial with DaVinci Resolve workflow breakdown.',
    tags: ['DaVinci Resolve', 'Color Science'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'e3',
    title: 'YouTube Growth Strategy',
    category: 'Educational',
    year: '2023',
    thumbnail: '/images/projects/edu-3.jpg',
    description: 'Educational content about YouTube algorithm, CTR optimization, and retention.',
    tags: ['Motion Graphics', 'Data Viz'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'e4',
    title: 'Premiere Pro Shortcuts',
    category: 'Educational',
    year: '2023',
    thumbnail: '/images/projects/edu-4.jpg',
    description: 'Quick tips video showcasing essential keyboard shortcuts for faster editing.',
    tags: ['Premiere Pro', 'Tips & Tricks'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'e5',
    title: 'Motion Graphics Crash Course',
    category: 'Educational',
    year: '2024',
    thumbnail: '/images/projects/edu-5.jpg',
    description: 'Beginner-friendly After Effects tutorial covering essential motion graphic techniques.',
    tags: ['After Effects', 'Tutorial'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'e6',
    title: 'Freelance Editing Business',
    category: 'Educational',
    year: '2024',
    thumbnail: '/images/projects/edu-6.jpg',
    description: 'How-to guide on building a $2K/month video editing freelance business.',
    tags: ['Business', 'Freelance'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'e7',
    title: 'Audio Mixing for Editors',
    category: 'Educational',
    year: '2023',
    thumbnail: '/images/projects/edu-7.jpg',
    description: 'Complete audio mixing tutorial for video editors — EQ, compression, and leveling.',
    tags: ['Audition', 'Audio Mix'],
    youtubeId: 'dQw4w9WgXcQ',
  },

  // ─── Business ───
  {
    id: 'b1',
    title: 'TechVision Ad Campaign',
    category: 'Business',
    year: '2024',
    thumbnail: '/images/projects/biz-1.jpg',
    description: 'High-energy product commercial with seamless transitions and motion design.',
    tags: ['Premiere Pro', 'Motion Graphics', 'Ad'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'b2',
    title: 'SaaS Product Demo',
    category: 'Business',
    year: '2024',
    thumbnail: '/images/projects/biz-2.jpg',
    description: 'Clean product demo video with screen recordings, annotations, and CTA overlays.',
    tags: ['Screen Record', 'After Effects'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'b3',
    title: 'Brand Story — Nova',
    category: 'Business',
    year: '2023',
    thumbnail: '/images/projects/biz-3.jpg',
    description: 'Corporate brand film blending storytelling with sleek motion graphics.',
    tags: ['Premiere Pro', 'After Effects', 'Color Grade'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'b4',
    title: 'E-Commerce Ad Set',
    category: 'Business',
    year: '2024',
    thumbnail: '/images/projects/biz-4.jpg',
    description: 'High-converting product ads for Facebook and Instagram with fast-paced cuts.',
    tags: ['Ad Creative', 'Social Media'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'b5',
    title: 'Real Estate Walkthrough',
    category: 'Business',
    year: '2023',
    thumbnail: '/images/projects/biz-5.jpg',
    description: 'Cinematic property tour with drone footage, transitions, and voice-over.',
    tags: ['Drone', 'Color Grade', 'VO'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'b6',
    title: 'Restaurant Promo',
    category: 'Business',
    year: '2023',
    thumbnail: '/images/projects/biz-6.jpg',
    description: 'Mouth-watering food commercial with slow-motion shots and warm color grade.',
    tags: ['Slow Motion', 'Color Grade'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'b7',
    title: 'Fitness App Launch',
    category: 'Business',
    year: '2024',
    thumbnail: '/images/projects/biz-7.jpg',
    description: 'Energetic app launch video with UI animations and lifestyle footage.',
    tags: ['After Effects', 'UI Animation'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'b8',
    title: 'Coaching VSL',
    category: 'Business',
    year: '2024',
    thumbnail: '/images/projects/biz-8.jpg',
    description: 'High-converting video sales letter with testimonials and call-to-action overlays.',
    tags: ['VSL', 'Premiere Pro', 'CTA'],
    youtubeId: 'dQw4w9WgXcQ',
  },

  // ─── Reels ───
  {
    id: 'r1',
    title: 'Viral Hook Reel',
    category: 'Reels',
    year: '2024',
    thumbnail: '/images/projects/reel-1.jpg',
    description: 'Scroll-stopping Instagram reel with kinetic text, zoom cuts, and trending audio.',
    tags: ['Reels', 'Kinetic Text', 'Trending'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'r2',
    title: 'Motivational Short',
    category: 'Reels',
    year: '2024',
    thumbnail: '/images/projects/reel-2.jpg',
    description: 'Cinematic motivational reel with epic music, text overlays, and fast transitions.',
    tags: ['Cinematic', 'Text Overlay'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'r3',
    title: 'Product Showcase Reel',
    category: 'Reels',
    year: '2024',
    thumbnail: '/images/projects/reel-3.jpg',
    description: 'Smooth product showcase reel with 3D-style transitions and beat sync.',
    tags: ['Beat Sync', 'Product', 'Transitions'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'r4',
    title: 'Day in the Life',
    category: 'Reels',
    year: '2023',
    thumbnail: '/images/projects/reel-4.jpg',
    description: 'Aesthetic day-in-the-life vlog edit with smooth transitions and warm tones.',
    tags: ['Vlog', 'Color Grade', 'Transitions'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'r5',
    title: 'Before/After Transformation',
    category: 'Reels',
    year: '2023',
    thumbnail: '/images/projects/reel-5.jpg',
    description: 'Viral before-after editing transformation reel with satisfying reveals.',
    tags: ['Before/After', 'VFX'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'r6',
    title: 'Travel Montage Short',
    category: 'Reels',
    year: '2024',
    thumbnail: '/images/projects/reel-6.jpg',
    description: 'Fast-paced travel montage with beat-synced cuts and cinematic color grading.',
    tags: ['Travel', 'Beat Sync', 'Color Grade'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'r7',
    title: 'Gym Motivation Edit',
    category: 'Reels',
    year: '2023',
    thumbnail: '/images/projects/reel-7.jpg',
    description: 'High-energy gym reel with slow-motion, speed ramps, and bass-heavy audio sync.',
    tags: ['Speed Ramp', 'Slow Motion'],
    youtubeId: 'dQw4w9WgXcQ',
  },
  {
    id: 'r8',
    title: 'Fashion Brand Reel',
    category: 'Reels',
    year: '2024',
    thumbnail: '/images/projects/reel-8.jpg',
    description: 'Elegant fashion brand reel with smooth pans, color grading, and minimal text.',
    tags: ['Fashion', 'Minimal', 'Color Grade'],
    youtubeId: 'dQw4w9WgXcQ',
  },

  // ─── Thumbnail / Graphic Design ───
  {
    id: 't1',
    title: 'YouTube Thumbnail — Finance',
    category: 'Thumbnail',
    year: '2024',
    thumbnail: '/images/projects/thumb-1.jpg',
    description: 'Eye-catching YouTube thumbnail with bold text, face cutout, and vibrant colors.',
    tags: ['Photoshop', 'Thumbnail'],
    imageSrc: '/images/projects/thumb-1.jpg',
  },
  {
    id: 't2',
    title: 'YouTube Thumbnail — Tech',
    category: 'Thumbnail',
    year: '2024',
    thumbnail: '/images/projects/thumb-2.jpg',
    description: 'Clean tech review thumbnail with product imagery and gradient background.',
    tags: ['Photoshop', 'Thumbnail'],
    imageSrc: '/images/projects/thumb-2.jpg',
  },
  {
    id: 't3',
    title: 'Podcast Cover Art',
    category: 'Thumbnail',
    year: '2024',
    thumbnail: '/images/projects/thumb-3.jpg',
    description: 'Bold podcast cover art with portrait, typography, and brand colors.',
    tags: ['Photoshop', 'Branding'],
    imageSrc: '/images/projects/thumb-3.jpg',
  },
  {
    id: 't4',
    title: 'Instagram Carousel Design',
    category: 'Thumbnail',
    year: '2023',
    thumbnail: '/images/projects/thumb-4.jpg',
    description: 'Educational carousel post design with consistent branding and clear visuals.',
    tags: ['Photoshop', 'Social Media'],
    imageSrc: '/images/projects/thumb-4.jpg',
  },
  {
    id: 't5',
    title: 'Course Banner Design',
    category: 'Thumbnail',
    year: '2024',
    thumbnail: '/images/projects/thumb-5.jpg',
    description: 'Online course banner with premium look, gradient accents, and CTA text.',
    tags: ['Photoshop', 'Banner'],
    imageSrc: '/images/projects/thumb-5.jpg',
  },
  {
    id: 't6',
    title: 'YouTube Thumbnail — Fitness',
    category: 'Thumbnail',
    year: '2023',
    thumbnail: '/images/projects/thumb-6.jpg',
    description: 'High-CTR fitness thumbnail with dramatic lighting and bold headline.',
    tags: ['Photoshop', 'Thumbnail'],
    imageSrc: '/images/projects/thumb-6.jpg',
  },
  {
    id: 't7',
    title: 'Brand Social Kit',
    category: 'Thumbnail',
    year: '2024',
    thumbnail: '/images/projects/thumb-7.jpg',
    description: 'Complete social media graphics kit — posts, stories, and highlight covers.',
    tags: ['Photoshop', 'Branding', 'Social'],
    imageSrc: '/images/projects/thumb-7.jpg',
  },
  {
    id: 't8',
    title: 'YouTube Thumbnail — Gaming',
    category: 'Thumbnail',
    year: '2023',
    thumbnail: '/images/projects/thumb-8.jpg',
    description: 'Vibrant gaming thumbnail with character art, effects, and bold text.',
    tags: ['Photoshop', 'Gaming'],
    imageSrc: '/images/projects/thumb-8.jpg',
  },
  {
    id: 't9',
    title: 'Event Poster Design',
    category: 'Thumbnail',
    year: '2024',
    thumbnail: '/images/projects/thumb-9.jpg',
    description: 'Modern event poster with clean typography, speaker photos, and gradient accents.',
    tags: ['Photoshop', 'Print Design'],
    imageSrc: '/images/projects/thumb-9.jpg',
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    company: 'Luminos Records',
    role: 'Creative Director',
    quote: 'The color grading on our music video was absolutely phenomenal. The final product exceeded all our expectations and blew up on social media.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Marcus Williams',
    company: 'TechVision Inc.',
    role: 'Marketing Manager',
    quote: 'Delivered the commercial on time and the quality was incredible. The motion graphics perfectly captured our brand identity.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Priya Sharma',
    company: 'Indie Films Co.',
    role: 'Film Director',
    quote: 'Working with this editor transformed my short film into something truly cinematic. The attention to detail in every cut was remarkable.',
    rating: 5,
  },
  {
    id: '4',
    name: 'David Park',
    company: 'Nova Brands',
    role: 'CEO',
    quote: 'Our brand film resonated deeply with our audience. The storytelling through editing was next level. Will definitely work together again.',
    rating: 5,
  },
  {
    id: '5',
    name: 'Emma Rodriguez',
    company: 'Soundwave Music',
    role: 'Artist Manager',
    quote: 'Three music videos done and each one better than the last. This editor understands the vision and brings it to life brilliantly.',
    rating: 5,
  },
]

export const SKILLS: Skill[] = [
  { name: 'Adobe Premiere Pro', level: 98, color: '#9999FF', icon: 'Pr' },
  { name: 'After Effects', level: 95, color: '#9999FF', icon: 'Ae' },
  { name: 'DaVinci Resolve', level: 90, color: '#FF6B35', icon: 'DR' },
  { name: 'Cinema 4D', level: 80, color: '#5CFF85', icon: 'C4D' },
  { name: 'Adobe Photoshop', level: 85, color: '#31A8FF', icon: 'Ps' },
  { name: 'Final Cut Pro', level: 78, color: '#E8E8E8', icon: 'FCP' },
  { name: 'Audition', level: 82, color: '#00E4BB', icon: 'Au' },
  { name: 'Lightroom', level: 88, color: '#31A8FF', icon: 'Lr' },
]

export const SERVICES: Service[] = [
  {
    number: '01',
    title: 'Video Editing & Post-Production',
    description: 'Complete post-production workflow from rough cut to final delivery, ensuring a polished and professional result.',
  },
  {
    number: '02',
    title: 'Color Grading & Correction',
    description: 'Transform your footage with cinematic color palettes, mood-enhancing LUTs, and precise color science.',
  },
  {
    number: '03',
    title: 'Motion Graphics & VFX',
    description: 'Dynamic motion graphics, visual effects, and animated titles that elevate your visual storytelling.',
  },
  {
    number: '04',
    title: 'Social Media Content',
    description: 'Optimized short-form content for Instagram Reels, TikTok, and YouTube Shorts with maximum impact.',
  },
  {
    number: '05',
    title: 'Wedding & Event Films',
    description: 'Cinematic wedding and event films that capture every emotion with artistic precision.',
  },
  {
    number: '06',
    title: 'Corporate Video Production',
    description: 'Professional corporate films, product demos, and brand stories that drive results.',
  },
]

export const NAV_LINKS = [
  { label: 'About', href: '#about' },
  { label: 'Services', href: '#services' },
  { label: 'Work', href: '#portfolio' },
  { label: 'Pricing', href: '#pricing' },
  { label: 'Testimonials', href: '#testimonials' },
  { label: 'Contact', href: '#contact' },
]
